/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubmissionService } from "../submission.service";
import { SubmissionCreateInput } from "./SubmissionCreateInput";
import { Submission } from "./Submission";
import { SubmissionFindManyArgs } from "./SubmissionFindManyArgs";
import { SubmissionWhereUniqueInput } from "./SubmissionWhereUniqueInput";
import { SubmissionUpdateInput } from "./SubmissionUpdateInput";
import { GradeFindManyArgs } from "../../grade/base/GradeFindManyArgs";
import { Grade } from "../../grade/base/Grade";
import { GradeWhereUniqueInput } from "../../grade/base/GradeWhereUniqueInput";

export class SubmissionControllerBase {
  constructor(protected readonly service: SubmissionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Submission })
  async createSubmission(
    @common.Body() data: SubmissionCreateInput
  ): Promise<Submission> {
    return await this.service.createSubmission({
      data: {
        ...data,

        assignment: data.assignment
          ? {
              connect: data.assignment,
            }
          : undefined,
      },
      select: {
        assignment: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        student: true,
        submissionDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Submission] })
  @ApiNestedQuery(SubmissionFindManyArgs)
  async submissions(@common.Req() request: Request): Promise<Submission[]> {
    const args = plainToClass(SubmissionFindManyArgs, request.query);
    return this.service.submissions({
      ...args,
      select: {
        assignment: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        student: true,
        submissionDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async submission(
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Submission | null> {
    const result = await this.service.submission({
      where: params,
      select: {
        assignment: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        student: true,
        submissionDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSubmission(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() data: SubmissionUpdateInput
  ): Promise<Submission | null> {
    try {
      return await this.service.updateSubmission({
        where: params,
        data: {
          ...data,

          assignment: data.assignment
            ? {
                connect: data.assignment,
              }
            : undefined,
        },
        select: {
          assignment: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          student: true,
          submissionDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSubmission(
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Submission | null> {
    try {
      return await this.service.deleteSubmission({
        where: params,
        select: {
          assignment: {
            select: {
              id: true,
            },
          },

          content: true,
          createdAt: true,
          id: true,
          student: true,
          submissionDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/grades")
  @ApiNestedQuery(GradeFindManyArgs)
  async findGrades(
    @common.Req() request: Request,
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Grade[]> {
    const query = plainToClass(GradeFindManyArgs, request.query);
    const results = await this.service.findGrades(params.id, {
      ...query,
      select: {
        comments: true,
        createdAt: true,
        grade: true,
        id: true,

        submission: {
          select: {
            id: true,
          },
        },

        teacher: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/grades")
  async connectGrades(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() body: GradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      grades: {
        connect: body,
      },
    };
    await this.service.updateSubmission({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/grades")
  async updateGrades(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() body: GradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      grades: {
        set: body,
      },
    };
    await this.service.updateSubmission({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/grades")
  async disconnectGrades(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() body: GradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      grades: {
        disconnect: body,
      },
    };
    await this.service.updateSubmission({
      where: params,
      data,
      select: { id: true },
    });
  }
}
